# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AGU AI
tagline: Artificial Intelligence Research At Abdullah Gul University
email: ai@agu.edu.tr
description: > # this means to ignore newlines until "baseurl:"
  Our overarching goal is to foster and promote AI research at AGU (Abdullah Gul University). AGU AI is a consolidated research group involving Computer Vision, Machine Learning - Artificial Intelligence, Biomedical Image Processing, Bioinformatics and Network researchers from the Abdullah Gul University.
baseurl: ""
url: "https://ai.agu.edu.tr"
author: Kasim Tasdemir
twitter:
  username: ai_group_agu
  card: summary
logo: /images/AGU_AI_logo.png
google_site_verification: v6tuyVzjyCT8_yy-GJmHPsydRLmV2ZexfaBUoHkdFHY

# Change environment to production before deploying.  
# If it is "development", google analytics wont work, a warning will appear on top.
# environment: development
environment: production

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-octicons
collections:
  people:
    output: true
    sort_by: sort_order
  projects:
    output: true
    sort_by: sort_order



